sudo: required

addons:
  apt:
    packages:
    - tree
    - docker-ce

services:
- docker

branches:
  except:
  - gh-pages

language: java

jdk:
- oraclejdk8

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk9
  - os: linux
    jdk: oraclejdk11
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: openjdk11

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

notifications:
  slack:
    rooms:
      secure: LKXvikO3XlnuUw5049VhO7zmQPg3SIXt8Jc2Q8GL6yTt8sh9ORhtwn9JTv8f9gnFJn8iEGSaKpotLrjIMaQKeZHWR6GgQ1jdlNo0TY6npzzzO1wFn5bxVEeZ2I+GRX5r0gsLp1bv95ra9eTfcjEgn7q/JDKiu0Z5ycXDoocjU2si22xx9wZQMztn44FLQFYiVwtvCMKmiRVpDXehfb094kVFPE4hKankpMjrTtKm4UpneVOBEKS/AUYH+Fo0n03MNip9p4hDnrryHclkR2nwofIbGRugfOWjYkgXKwuA3EZ3DSGX+Al5y872oVQNvIehD3VM9CcF5BSc/S0+CPulGye70OTeHWWwQVSVEfZPX37pbE9sz6Il8n40VMpSq3UR3J2hYGlIJmhzaiwExxdLmqemhpP5bINtZOEKYaf2PNs+Lj8IHs8p9NEDJiEUqC6TUtxJUPdZyGHiPJxSpWiwYFaUB2hODLc5+jtBHdtGorXs9RWA/6NC2+HDYyzsAjs37y1B9uPV2hj9rmUi0UEtf92OQXZ8+ISjPdHf5djMU9b0dFcwaxnSjWLElOe9IIiWGd0pY6UT1lALDdA/QpbEuqwwNwf6JEZz2kFjKZuacVrZdcqSYgtn5A9XXS6qtgCSQKHYdlArAnJDgz7j7A6CdGRZqcMViC/DBuxuLMKrQLY=
    on_success: always
    on_failure: always
    on_pull_requests: true

deploy:
- provider: script
  script: ./gradlew bintrayUpload
            -PbintrayUser=$BINTRAY_USER
            -PbintrayApiKey=$BINTRAY_KEY
            -PbintrayRepo=$BINTRAY_REPO
  on:
    jdk: oraclejdk11
    branch: master
    tags: true

- provider: script
  script: ./gradlew pushDockerImage
            -PdockerHubUsername=$DOCKER_HUB_USERNAME
            -PdockerHubPassword=$DOCKER_HUB_PASSWORD
            -PdockerHubEmail=$DOCKER_HUB_EMAIL
            -PdockerHubMaintainer=$DOCKER_HUB_MAINTAINER
  on:
    jdk: oraclejdk11
    branch: master
    tags: true

after_deploy:
- echo 'Successful deployment'